// <auto-generated />
namespace Adminodash.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig4354 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig4354));
        
        string IMigrationMetadata.Id
        {
            get { return "202403031822367_mig4354"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
